#include "evt_cmd.h"
#include "mod.h"
#include "patch.h"
#include "evtpatch.h"
#include "main_scripting.h"
#include "npc_rpgdrv.h"
#include "oChunks.h"

#include <spm/rel/an.h>
#include <spm/evtmgr.h>
#include <spm/evt_ac.h>
#include <spm/evt_msg.h>
#include <spm/evt_mario.h>
#include <spm/evt_pouch.h>
#include <spm/evt_fade.h>
#include <spm/evt_map.h>
#include <spm/evt_mobj.h>
#include <spm/evt_paper.h>
#include <spm/evt_img.h>
#include <spm/evt_env.h>
#include <spm/evt_eff.h>
#include <spm/evt_snd.h>
#include <spm/evt_cam.h>
#include <spm/evt_sub.h>
#include <spm/evt_npc.h>
#include <spm/evt_door.h>
#include <spm/evt_case.h>
#include <spm/evt_pouch.h>
#include <spm/evt_seq.h>
#include <spm/rel/an2_08.h>
#include <spm/rel/sp4_13.h>
#include <spm/wpadmgr.h>
#include <spm/map_data.h>
#include <spm/seqdrv.h>
#include <spm/seq_game.h>
#include <spm/npcdrv.h>
#include <spm/mario.h>
#include <spm/mario_pouch.h>
#include <spm/seqdef.h>
#include <wii/os/OSError.h>
#include <patch.h>
#include <string>

using namespace spm::npcdrv;
using namespace spm::evt_npc;

namespace mod {
spm::evtmgr::EvtScriptCode* onSpawn = spm::npcdrv::npcEnemyTemplates[183].onSpawnScript;
spm::evtmgr::EvtScriptCode* chonkyAttackScript = getInstructionEvtArg(onSpawn, 41, 3);
spm::evtmgr::EvtScriptCode* throwScript = getInstructionEvtArg(chonkyAttackScript, 182, 0);
spm::evtmgr::EvtScriptCode* throwScriptOffset = evtpatch::getLineOffset(throwScript, 135);
NPCTribeAnimDef animsChunks[] = {
    {0, "S_1"},
    {1, "W_1"},
    {2, "R_1"},
    {3, "T_5"},
    {4, "D_1"},
    {8, "A_2a"},
    {9, "A_2b"},
    {10, "O_1a"},
    {11, "O_1b"},
    {12, "O_1c"},
    {13, "O_5"},
    {14, "S_5"},
    {25, "A_4a"},
    {26, "J_1"},
    {27, "J_2"},
    {28, "J_3"},
    {29, "J_4"},
    {30, "A_1a"},
    {31, "A_1b"},
    {32, "A_1c"},
    {33, "A_1d"},
    {34, "T_8a"},
    {35, "T_8b"},
    {54, "O_6a"},
    {62, "A_4b"},
    {63, "A_4c"},
    {64, "A_4d"},
    {-1, nullptr}
  };

  NPCTribeAnimDef * getChunksAnims()
  {
    return animsChunks;
  }

const char * chunks_dialogue_1 = "<dq>\n"
"<p>\n"
"O'Chunks taunts Mario!\n"
"<o>\n";

const char * chunks_dialogue_2 = "<dq>\n"
"<p>\n"
"O'Chunks flexes for the\n"
"audience!\n"
"<o>\n";

const char * tippi_dialogue_1 = "<p><fairy>\n"
"We're going to beat you\n"
"anyways... Just give up!\n"
"<k>\n";

const char * chunks_dialogue_3 = "<p>\n"
"How dare yeh insult me honor??\n"
"I am the door that won't take\n"
"yer key!\n"
"<k>\n";

const char * chunks_dialogue_4 = "<dq>\n"
"<p>\n"
"O'Chunks challenges Mario\n"
"to a thumb war!\n"
"Mario politely declines.\n"
"<o>\n";

const char * chunks_dialogue_5 = "<dq>\n"
"<p>\n"
"O'Chunks is getting weary...\n"
"<o>\n";

const char * chunks_dialogue_6 = "<dq>\n"
"<p>\n"
"O'Chunks texts Mimi to stop\n"
"stealing his nunchucks.\n"
"Tippi shakes her head.\n"
"<o>\n";


const char * chunks_dialogue_7 = "<dq>\n"
"<p>\n"
"O'Chunks locks in!\n"
"<o>\n";

  EVT_BEGIN(chunks_start_fight)
    //USER_FUNC(spm::evt_mobj::evt_mobj_blk, 4, PTR("mobj3"), 0, 0, 0, 0, 0, 0)
    USER_FUNC(start_boss_fight, 270)
    WAIT_MSEC(1000)
    USER_FUNC(evt_npc_set_position, PTR("dodon"), 0, -1000, 0)
  RETURN()
  EVT_END()

  EVT_BEGIN(chunks_start_fight_fwd)
    RUN_EVT(chunks_start_fight)
  RETURN_FROM_CALL()

  EVT_BEGIN(chunks_on_spawn)
    USER_FUNC(evt_npc_set_disp_callback, LW(15), PTR(oChunksNpcDispCb))
    USER_FUNC(spm::evt_mobj::evt_mobj_blk, 4, PTR("mobj2"), 0, 0, 0, 0, 0, 0)
    ADDF(LW(1), 5)
    USER_FUNC(spm::evt_mobj::evt_mobj_set_position, PTR("mobj2"), LW(0), LW(1), LW(2))
    SUBF(LW(1), 5)
    USER_FUNC(spm::evt_mobj::evt_mobj_set_scale, PTR("mobj2"), FLOAT(4.0), FLOAT(2.4), FLOAT(4.0))
    USER_FUNC(mobjChangeAnimPoseName, PTR("mobj2"), PTR("MOBJ_su_blank"))
    USER_FUNC(set_npc_as_me, LW(15))
    USER_FUNC(func_801f0d30)
  RETURN()
  EVT_END()

EVT_BEGIN(chunks_jump_land_anims)
  USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_BS_DDN_LANDING1"))
  USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_BS_DDN_STIFFEN1"))
  //USER_FUNC(spm::evt_snd::evt_snd_sfx_wait_name, PTR("SFX_BS_DDN_LANDING1"))
  USER_FUNC(evt_npc_set_anim, LW(15), 33, 1)
  USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
  USER_FUNC(evt_npc_set_anim, LW(15), 10, 1)
  USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
  USER_FUNC(evt_npc_set_anim, LW(15), 11, 1)
  USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
  USER_FUNC(evt_npc_set_anim, LW(15), 12, 1)
  USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
RETURN()
EVT_END()

EVT_BEGIN(chunks_dialogue)
  USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 14, LW(0))
  SWITCH(LW(0))
    CASE_EQUAL(0)
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_1))
    CASE_EQUAL(1)
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_2))
    CASE_EQUAL(2)
      USER_FUNC(spm::evt_msg::evt_msg_print, 1, PTR(tippi_dialogue_1), 0, PTR("__guide__"))
      INLINE_EVT()
          WAIT_MSEC(100)
          USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_EVT_DDN_JIDANDA1"))
          USER_FUNC(spm::evt_cam::evt_cam_shake, 5, FLOAT(1.19921875), FLOAT(1.19921875), FLOAT(0.0), 500, 0)
      END_INLINE()
      USER_FUNC(evt_npc_set_anim, LW(15), 13, 1)
      USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
      USER_FUNC(evt_npc_set_anim, LW(15), 14, 1)
      USER_FUNC(spm::evt_msg::evt_msg_print, 1, PTR(chunks_dialogue_3), 0, LW(15))
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_4))
    CASE_EQUAL(3)
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_5))
    CASE_EQUAL(4)
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_6))
    CASE_EQUAL(5)
      USER_FUNC(rpg_set_dialogue, PTR(chunks_dialogue_7))
  END_SWITCH()
  ADD(LW(0), 1)
  USER_FUNC(spm::evt_npc::evt_npc_set_unitwork, LW(15), 14, LW(0))
RETURN()
EVT_END()

EVT_BEGIN(chunks_attack)
    USER_FUNC(spm::evt_mobj::evt_mobj_hit_onoff, 0, PTR("mobj2"))
    RUN_CHILD_EVT(chunks_dialogue)
    USER_FUNC(spm::evt_sub::evt_sub_random, 1, LW(0))
    SWITCH(LW(0))
      CASE_EQUAL(0)
          USER_FUNC(evt_npc_get_position, LW(15), LW(5), LW(6), LW(7))
          USER_FUNC(spm::evt_mario::evt_mario_get_pos, LW(0), LW(1), LW(2))
          SET(LW(5), LW(0))
          ADD(LW(5), 75)
          INLINE_EVT()
            SET(LW(13), UW(3))
            SUB(LW(13), 25)
            USER_FUNC(spm::evt_cam::evt_cam3d_evt_zoom_in, 0, LW(5), EVT_NULLPTR, LW(13), LW(5), EVT_NULLPTR, 200, 1000, 11)
          END_INLINE()
          USER_FUNC(evt_npc_set_anim, LW(15), 8, 1)
          USER_FUNC(evt_npc_wait_anim_end, LW(15), 0)
          USER_FUNC(evt_npc_set_anim, LW(15), 9, 1)
          USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_RUN1"), LW(15))
          USER_FUNC(spm::evt_snd::evt_snd_get_last_sfx_id, LW(14))
          INLINE_EVT_ID(LW(13))
              DO(0)
                  USER_FUNC(spm::evt_cam::evt_cam_shake, 5, FLOAT(1.0), FLOAT(1.0), FLOAT(0.0), 150, 0)
                  WAIT_FRM(1)
              WHILE()
          END_INLINE()
          INLINE_EVT()
            SET(LW(10), 0)
            LBL(1)
              IF_SMALL(LW(10), 43)
                USER_FUNC(check_pressed_b_ac, LW(11))
                IF_EQUAL(LW(11), 1)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_2"), 0)
                  WAIT_FRM(3)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_1"), 0)
                  GOTO(2)
                END_IF()
              ELSE()
                USER_FUNC(check_pressed_b_ac, LW(11))
                IF_EQUAL(LW(11), 1)
                  USER_FUNC(ac_success_toggle)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_2"), 0)
                  IF_LARGE_EQUAL(LW(10), 50)
                    USER_FUNC(superguard_toggle)
                    USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("J_1A"), 0)
                  END_IF()
                  GOTO(2)
                END_IF()
              END_IF()
              WAIT_FRM(1)
              ADD(LW(10), 1)
              IF_EQUAL(LW(10), 53)
                GOTO(2)
              END_IF()
            GOTO(1)
            LBL(2)
          END_INLINE()
          USER_FUNC(spm::evt_mario::evt_mario_get_pos, LW(0), LW(1), LW(2))
          USER_FUNC(evt_npc_walk_to, LW(15), UW(4), LW(1), LW(2), FLOAT(250.0), 0, 0, 0)
          USER_FUNC(spm::evt_snd::evt_snd_sfxoff, LW(14))
          DELETE_EVT(LW(13))
          USER_FUNC(spm::an2_08::evt_rpg_char_get, LW(3))
          USER_FUNC(check_ac_success, LW(11))
          IF_EQUAL(LW(11), 1)
            USER_FUNC(check_superguard_success, LW(11))
            IF_EQUAL(LW(11), 1)
            USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_F_COUNTER_REBOUND1"))
            USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("J_1B"), 0)
            USER_FUNC(evt_npc_set_anim, LW(15), 4, 1)
            USER_FUNC(spm::evt_mario::evt_mario_jump_to, LW(0), LW(6), LW(7), 20, 300)
            BROTHER_EVT_ID(LW(4))
              RUN_CHILD_EVT(superguard_stylish)
            END_BROTHER()
            WAIT_MSEC(500)
            ELSE()
              SET(LW(11), 1)
              USER_FUNC(spm::an2_08::evt_rpg_calc_mario_damage, 1, LW(10))
              SUB(LW(10), 2)
              IF_SMALL(LW(10), 0)
                SET(LW(10), 0)
              END_IF()
              RUN_CHILD_EVT(mod::marioRPGtakeDamage)
              USER_FUNC(spm::an2_08::evt_rpg_mario_take_damage, LW(10), 0, LW(0))
            END_IF()
          ELSE()
            USER_FUNC(spm::an2_08::evt_rpg_calc_mario_damage, 1, LW(10))
            RUN_CHILD_EVT(mod::marioRPGtakeDamage)
            USER_FUNC(spm::an2_08::evt_rpg_mario_take_damage, LW(10), 0, LW(0))
          END_IF()
      CASE_EQUAL(1)
        USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_JUMP1"), LW(15))
        USER_FUNC(evt_npc_set_anim, LW(15), 26, 1)
        USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
        INLINE_EVT()
          USER_FUNC(evt_npc_set_anim, LW(15), 27, 1)
          WAIT_FRM(30)
          USER_FUNC(evt_npc_set_anim, LW(15), 28, 1)
        END_INLINE()
        USER_FUNC(spm::evt_mario::evt_mario_get_pos, LW(0), LW(1), LW(2))
        ADD(LW(1), 100)
        //USER_FUNC(evt_npc_arc_to, LW(15), LW(0), LW(1), LW(2), 1100, 0, FLOAT(550.0), 0, 256, 0)
        USER_FUNC(evt_npc_jump_to, LW(15), LW(0), LW(1), LW(2), 100, FLOAT(1000.0))
        USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_ROUND1"), LW(15))
        USER_FUNC(evt_npc_set_anim, LW(15), 30, 1)
        USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
        USER_FUNC(evt_npc_wait_for, LW(15), 200)
        USER_FUNC(evt_npc_set_anim, LW(15), 31, 1)
        SUB(LW(1), 100)
          INLINE_EVT()
            SET(LW(10), 0)
            LBL(1)
              IF_SMALL(LW(10), 5)
                USER_FUNC(check_pressed_b_ac, LW(11))
                IF_EQUAL(LW(11), 1)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_2"), 0)
                  WAIT_FRM(3)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_1"), 0)
                  GOTO(2)
                END_IF()
              ELSE()
                USER_FUNC(check_pressed_b_ac, LW(11))
                IF_EQUAL(LW(11), 1)
                  USER_FUNC(ac_success_toggle)
                  USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("S_2"), 0)
                  IF_LARGE_EQUAL(LW(10), 10)
                    USER_FUNC(superguard_toggle)
                    USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("J_1A"), 0)
                  END_IF()
                  GOTO(2)
                END_IF()
              END_IF()
              WAIT_FRM(1)
              ADD(LW(10), 1)
              IF_EQUAL(LW(10), 14)
                GOTO(2)
              END_IF()
            GOTO(1)
            LBL(2)
          END_INLINE()
        USER_FUNC(evt_npc_glide_to, LW(15), LW(0), LW(1), LW(2), 0, FLOAT(600.0), 0, 0, 5, 0)
        USER_FUNC(check_ac_success, LW(11))
          IF_EQUAL(LW(11), 1)
            USER_FUNC(check_superguard_success, LW(11))
            IF_EQUAL(LW(11), 1)
              USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_F_COUNTER_REBOUND1"))
              USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("J_1B"), 0)
              USER_FUNC(evt_npc_set_anim, LW(15), 4, 1)
              USER_FUNC(spm::evt_mario::evt_mario_jump_to, LW(0), LW(6), LW(7), 20, 300)
              BROTHER_EVT_ID(LW(4))
                RUN_CHILD_EVT(superguard_stylish)
              END_BROTHER()
              WAIT_MSEC(500)
            ELSE()
              SET(LW(11), 1)
              USER_FUNC(spm::an2_08::evt_rpg_calc_mario_damage, 1, LW(10))
              SUB(LW(10), 2)
              IF_SMALL(LW(10), 0)
                SET(LW(10), 0)
              END_IF()
              INLINE_EVT()
                USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_4"), 0)
                RUN_CHILD_EVT(mod::marioRPGtakeDamage)
                USER_FUNC(spm::an2_08::evt_rpg_mario_take_damage, LW(10), 0, LW(0))
              END_INLINE()
              RUN_CHILD_EVT(chunks_jump_land_anims)
            END_IF()
          ELSE()
            SET(LW(11), 1)
            INLINE_EVT()
              USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_4"), 0)
              USER_FUNC(spm::an2_08::evt_rpg_calc_mario_damage, 1, LW(10))
              RUN_CHILD_EVT(mod::marioRPGtakeDamage)
              USER_FUNC(spm::an2_08::evt_rpg_mario_take_damage, LW(10), 0, LW(0))
            END_INLINE()
            RUN_CHILD_EVT(chunks_jump_land_anims)
          END_IF()
    END_SWITCH()
    USER_FUNC(evt_npc_set_anim, LW(15), 2, 1)
    ADD(LW(5), 150)
    INLINE_EVT()
      USER_FUNC(spm::evt_cam::evt_cam3d_evt_zoom_in, 0, UW(1), EVT_NULLPTR, UW(3), UW(1), EVT_NULLPTR, 200, 1000, 11)
    END_INLINE()
    USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 0, LW(0))
    USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 1, LW(1))
    USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 2, LW(2))
    USER_FUNC(evt_npc_walk_to, LW(15), LW(0), LW(1), LW(2), FLOAT(240.0), 0, 0, 0)
    USER_FUNC(evt_npc_set_anim, LW(15), 0, 1)
    USER_FUNC(ac_success_reset)
    LBL(5)
    CHK_EVT(LW(4), LW(0))
    IF_EQUAL(LW(0), 0)
      RETURN()
    END_IF()
    WAIT_FRM(1)
    GOTO(5)
  EVT_END()


  EVT_BEGIN(chunks_throw)
    USER_FUNC(evt_npc_set_unitwork, LW(15), 4, 1)
    BROTHER_EVT_ID(LW(13))
        DO(0)
            USER_FUNC(evt_npc_get_unitwork, LW(15), 4, LW(0))
            IF_NOT_EQUAL(LW(0), 0)
                USER_FUNC(spm::evt_cam::func_800e01f8)
                USER_FUNC(func_801f2af8)
                DO_BREAK()
            END_IF()
            WAIT_FRM(1)
        WHILE()
    END_BROTHER()
    USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("E_4"), 0)
    USER_FUNC(spm::evt_mobj::evt_mobj_hit_onoff, 0, PTR("mobj2"))
    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_THROW_ROLL1"), LW(15))
    USER_FUNC(evt_npc_set_anim, LW(15), 62, 1)
    USER_FUNC(evt_npc_wait_for, LW(15), 1000)
    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_THROW_ROLL2"), LW(15))
    USER_FUNC(spm::evt_snd::evt_snd_get_last_sfx_id, LW(14))
    //USER_FUNC(evt_npc_set_partswork, LW(15), 1, 0, LW(14))
    USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
    USER_FUNC(evt_npc_set_anim, LW(15), 63, 1)
    USER_FUNC(evt_npc_wait_for, LW(15), 800)
    USER_FUNC(spm::evt_snd::evt_snd_sfxoff, LW(14))
    //USER_FUNC(evt_npc_set_partswork, LW(15), 1, 0, -1)
    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_THROW_ROLL3"), LW(15))
    USER_FUNC(evt_npc_set_anim, LW(15), 64, 1)
    BROTHER_EVT()
        USER_FUNC(evt_npc_wait_for, LW(15), 1400)
        USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR("SFX_BS_DDN_THROW_ROLL4"), LW(15))
    END_BROTHER()
    USER_FUNC(evt_npc_wait_for, LW(15), 166)
    DELETE_EVT(LW(13))
    //USER_FUNC(FUN_801f2664)
    BROTHER_EVT_ID(LW(14))
        USER_FUNC(spm::evt_mario::evt_mario_flag8_onoff, 1, 2)
        USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_1"), 0)
        //INLINE_EVT_ID(LW(13))
          USER_FUNC(func_801f1880, LW(3), LW(5))
        //END_INLINE()
        //WAIT_MSEC(8000)
        //DELETE_EVT(LW(13))
        USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 0, LW(0))
        SET(LW(0), UW(4))
        ADD(LW(0), 125)
        USER_FUNC(spm::evt_mario::evt_mario_jump_to, LW(0), FLOAT(0.0), FLOAT(0.0), 80, 700)
        //USER_FUNC(spm::evt_mario::evt_mario_set_pos, LW(0), FLOAT(0.0), FLOAT(0.0))
        SUBF(LW(0), FLOAT(40.0))
        WAIT_FRM(1)
        //USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_5"), 0)
        //USER_FUNC(func_801f2344, LW(3), LW(5), 20, 300)
        //USER_FUNC(evt_npc_wait_for, LW(15), 100)
        //USER_FUNC(FUN_8010bfa8, LW(15), 0)
        USER_FUNC(ac_success_reset)
        USER_FUNC(spm::an2_08::evt_rpg_calc_mario_damage, UW(0), LW(10))
        //RUN_CHILD_EVT(mod::marioRPGtakeDamage)
        USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_4"), 0)
        USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_P_MARIO_DAMAGE1"))
        USER_FUNC(spm::evt_snd::evt_snd_sfxon_character, PTR("SFX_P_V_MARIO_DAMEGE1"), PTR("SFX_P_V_PEACH_DAMEGE1"), PTR("SFX_P_V_KOOPA_DAMEGE1"), PTR("SFX_P_V_LUIGI_DAMEGE1"))
        USER_FUNC(displayDamage, LW(0), FLOAT(0.0), FLOAT(10.0), LW(10))
        USER_FUNC(spm::an2_08::evt_rpg_mario_take_damage, LW(10), 0, LW(0))
        //USER_FUNC(evt_npc_wait_for, LW(15), 30)
        USER_FUNC(spm::evt_mario::func_800f1a4c, LW(0))
        IF_EQUAL(LW(0), 24)
            USER_FUNC(spm::evt_mario::evt_mario_set_pose, PTR("D_1"), 0)
        END_IF()
        //USER_FUNC(evt_npc_wait_for, LW(15), 300)
        SET(LW(13), -1)
        /*USER_FUNC(spm::evt_sub::evt_sub_random, 2, LW(0))
        SWITCH(LW(0))
            CASE_EQUAL(0)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        SETF(LW(1), FLOAT(60.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(350.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 600, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        SETF(LW(1), FLOAT(60.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(150.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 600, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 600)
                USER_FUNC(evt_npc_set_anim, LW(15), 36, 1)
                USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
                USER_FUNC(FUN_80104c10, LW(15), 23, LW(5))
                IF_EQUAL(LW(5), 2)
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_DRUMING1_FAST_8033e328), LW(15))
                ELSE()
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_DRUMING1_8033e348), LW(15))
                END_IF()
                USER_FUNC(evt_snd_get_last_sfx_id, LW(13))
                USER_FUNC(FUN_801f3028, LW(10), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 37, 1)
                USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 39, 1)
                USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
                USER_FUNC(FUN_801f14cc)
                USER_FUNC(evt_snd_sfxoff, LW(13))
                SET(LW(13), -1)
                USER_FUNC(FUN_801f3028, LW(10), 0)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_cam_zoom_to_coords, 800, 11)
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 1000)
                USER_FUNC(evt_npc_set_anim, LW(15), 38, 1)
                USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
            CASE_EQUAL(1)
                USER_FUNC(FUN_80104c10, LW(15), 23, LW(5))
                IF_EQUAL(LW(5), 2)
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_MUSCLE1_FAST_8033e364), LW(15))
                ELSE()
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_MUSCLE1_8033e388), LW(15))
                END_IF()
                USER_FUNC(evt_npc_set_anim, LW(15), 40, 1)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(551.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 83, 534, LW(3), 83, -16, 333, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(351.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 333, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 333)
                USER_FUNC(FUN_801f3028, LW(10), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 41, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 666)
                USER_FUNC(FUN_801f3028, LW(10), 0)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_set_anim, LW(15), 42, 1)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(449.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 83, 534, LW(3), 83, -16, 333, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(249.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 333, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 333)
                USER_FUNC(FUN_801f3028, LW(10), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 43, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 666)
                USER_FUNC(FUN_801f3028, LW(10), 0)
                USER_FUNC(evt_npc_wait_for, LW(15), 500)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(551.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 100, 644, LW(3), 100, -16, 333, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(351.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 333, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_set_anim, LW(15), 44, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 666)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(350.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 60, 350, LW(3), 60, 0, 666, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(150.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 666, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 666)
                USER_FUNC(FUN_801f3028, LW(10), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 45, 1)
                USER_FUNC(FUN_801f14cc)
                USER_FUNC(FUN_801f3028, LW(10), 0)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_cam_zoom_to_coords, 800, 11)
                END_IF()
                USER_FUNC(evt_npc_set_anim, LW(15), 46, 1)
                USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 666)
            CASE_ETC()
                USER_FUNC(FUN_80104c10, LW(15), 23, LW(5))
                IF_EQUAL(LW(5), 2)
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_BAKA1_FAST_8033e3a0), LW(15))
                ELSE()
                    USER_FUNC(spm::evt_snd::evt_snd_sfxon_npc, PTR(&s_SFX_BS_DDN_POSE_BAKA1_8033e3bc), LW(15))
                END_IF()
                USER_FUNC(evt_npc_set_anim, LW(15), 47, 1)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(449.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 83, 534, LW(3), 83, -16, 333, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(249.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 333, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 333)
                USER_FUNC(evt_npc_set_anim, LW(15), 48, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 2000)
                USER_FUNC(evt_npc_wait_for, LW(15), 166)
                USER_FUNC(evt_npc_set_anim, LW(15), 49, 1)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(551.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 100, 644, LW(3), 100, -16, 166, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(351.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 166, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_set_anim, LW(15), 50, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 250)
                USER_FUNC(evt_npc_set_anim, LW(15), 51, 1)
                USER_FUNC(evt_npc_wait_for, LW(15), 500)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_npc_check_3d, LW(15), LW(0))
                    IF_EQUAL(LW(0), 0)
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        ADDF(LW(2), FLOAT(350.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), 60, 350, LW(3), 60, 0, 333, 11)
                    ELSE()
                        USER_FUNC(evt_npc_get_position, LW(15), LW(0), LW(1), LW(2))
                        ADDF(LW(1), FLOAT(70.0))
                        SETF(LW(3), LW(0))
                        SETF(LW(4), LW(1))
                        SETF(LW(5), LW(2))
                        SUBF(LW(0), FLOAT(150.0))
                        USER_FUNC(evt_cam3d_evt_zoom_in, -1, LW(0), LW(1), LW(2), LW(3), LW(4), LW(5), 333, 11)
                    END_IF()
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 333)
                USER_FUNC(FUN_801f3028, LW(10), 1)
                USER_FUNC(evt_npc_set_anim, LW(15), 52, 1)
                USER_FUNC(FUN_801f14cc)
                USER_FUNC(FUN_801f3028, LW(10), 0)
                USER_FUNC(evt_npc_set_anim, LW(15), 53, 1)
                USER_FUNC(FUN_800f1a4c, LW(0))
                IF_NOT_EQUAL(LW(0), 24)
                    USER_FUNC(evt_cam_zoom_to_coords, 800, 11)
                END_IF()
                USER_FUNC(evt_npc_wait_for, LW(15), 1000)
        END_SWITCH()
        USER_FUNC(FUN_800f1a4c, LW(0))
        IF_NOT_EQUAL(LW(0), 24)
            USER_FUNC(evt_mario_set_pose, PTR(&unk_805b4840), 0)
        END_IF()
        USER_FUNC(evt_npc_wait_for, LW(15), 200)
        USER_FUNC(evt_mario_flag8_onoff, 0, 2)
        USER_FUNC(evt_cam_flag_onoff, 0, 11, 16384)
        IF_NOT_EQUAL(LW(13), -1)
            USER_FUNC(evt_snd_sfxoff, LW(13))
        END_IF()*/
    END_BROTHER()
    USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
    USER_FUNC(evt_npc_set_anim, LW(15), 54, 1)
    USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
    USER_FUNC(evt_npc_set_anim, LW(15), 54, 1)
    USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
    USER_FUNC(evt_npc_set_anim, LW(15), 34, 1)
    USER_FUNC(evt_npc_wait_anim_end, LW(15), 1)
    USER_FUNC(evt_npc_set_anim, LW(15), 35, 1)
    DO(0)
        CHK_EVT(LW(14), LW(0))
        IF_EQUAL(LW(0), 0)
            DO_BREAK()
        END_IF()
        WAIT_FRM(1)
    WHILE()
    USER_FUNC(spm::evt_mario::evt_mario_flag8_onoff, 0, 2)
    USER_FUNC(spm::evt_npc::evt_npc_get_unitwork, LW(15), 0, LW(0))
    USER_FUNC(evt_npc_set_position, LW(15), LW(0), 0, 0)
    WAIT_FRM(60)
    RETURN()
  EVT_END()

  EVT_BEGIN(chunks_onhit)
    USER_FUNC(ac_success_reset)
    USER_FUNC(spm::evt_mobj::evt_mobj_hit_onoff, 1, PTR("mobj2"))
    SET(LW(10), 0)
    INLINE_EVT()
    LBL(1)
      IF_SMALL(LW(10), 27)
        USER_FUNC(check_pressed_b_ac, LW(11))
        IF_EQUAL(LW(11), 1)
          GOTO(2)
        END_IF()
      ELSE()
        USER_FUNC(check_pressed_b_ac, LW(11))
        IF_EQUAL(LW(11), 1)
          USER_FUNC(ac_success_toggle)
          GOTO(2)
        END_IF()
      END_IF()
      WAIT_FRM(1)
      ADD(LW(10), 1)
      IF_EQUAL(LW(10), 30)
        GOTO(2)
      END_IF()
    GOTO(1)
    LBL(2)
    END_INLINE()
    INLINE_EVT()
      DO(0)
        ADD(LW(10), 1)
        WAIT_FRM(1)
        IF_EQUAL(LW(10), 20)
          USER_FUNC(evt_npc_set_anim, LW(15), 25, 1)
          DO_BREAK()
        END_IF()
      WHILE()
    END_INLINE()
    ADDF(LW(5), FLOAT(0.0))
    ADDF(LW(6), FLOAT(70.0))
    ADDF(LW(7), FLOAT(10.0))
    USER_FUNC(spm::evt_mario::func_800f119c, LW(5), LW(6), LW(7), 60, 500)
    USER_FUNC(check_ac_success, LW(11))
    USER_FUNC(spm::an2_08::evt_rpg_calc_damage_to_enemy, LW(2), 0, LW(10))
    IF_EQUAL(LW(11), 1)
      USER_FUNC(spm::evt_snd::evt_snd_sfxon_character, PTR("SFX_P_V_MARIO_ATTACK1"), PTR("SFX_P_V_PEACH_ATTACK1"), PTR("SFX_P_V_KOOPA_ATTACK1"), PTR("SFX_P_V_LUIGI_ATTACK1"))
      USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_E_SMASH1"))
      USER_FUNC(spm::an2_08::evt_rpg_enemy_take_damage, LW(2), LW(10), 0, LW(0))
      USER_FUNC(displayDamage, LW(5), LW(6), LW(7), LW(10))
      RUN_EVT(damageAnims)
      USER_FUNC(spm::evt_mario::evt_mario_jump_to, LW(5), LW(6), LW(7), 80, 700)
      USER_FUNC(displayDamage, LW(5), LW(6), LW(7), LW(10))
      USER_FUNC(spm::evt_snd::evt_snd_sfxon_character, PTR("SFX_P_V_MARIO_ATTACK1"), PTR("SFX_P_V_PEACH_ATTACK1"), PTR("SFX_P_V_KOOPA_ATTACK1"), PTR("SFX_P_V_LUIGI_ATTACK1"))
      USER_FUNC(spm::evt_snd::evt_snd_sfxon, PTR("SFX_E_SMASH1"))
      USER_FUNC(spm::an2_08::evt_rpg_enemy_take_damage, LW(2), LW(10), 0, LW(0))
      RUN_EVT(damageAnims)
    ELSE()
      USER_FUNC(set_npc_as_me, LW(15))
      RUN_CHILD_EVT(chunks_throw)
      USER_FUNC(mario_chg_motion, 0)
    END_IF()
    USER_FUNC(spm::evt_mobj::evt_mobj_hit_onoff, 0, PTR("mobj2"))
  USER_FUNC(ac_success_reset)
  RETURN()
  EVT_END()

  void chunks_main()
  {
    npcTribes[270].attackStrength = 2;
    npcTribes[270].maxHp = 20;
    spm::map_data::MapData * he3_04_md = spm::map_data::mapDataPtr("he3_04");
    spm::evtmgr::EvtScriptCode* chunks_fight_setup_evt = getInstructionEvtArg(he3_04_md->initScript, 28, 0);
    spm::evtmgr::EvtScriptCode* chunks_fight_death_evt = getInstructionEvtArg(chunks_fight_setup_evt, 167, 3);
    evtpatch::hookEvtReplace(chunks_fight_setup_evt, 173, (spm::evtmgr::EvtScriptCode*)chunks_start_fight_fwd);
    evtpatch::hookEvtReplace(chunks_fight_setup_evt, 168, (spm::evtmgr::EvtScriptCode*)insertNop);
    evtpatch::hookEvtReplace(chunks_fight_setup_evt, 167, (spm::evtmgr::EvtScriptCode*)insertNop);
    evtpatch::hookEvtReplace(chunks_fight_setup_evt, 166, (spm::evtmgr::EvtScriptCode*)insertNop);
    
  }

}
